### PR TITLE
Quickfix for building error

### PR DESCRIPTION
**Pull request by satymshrma**
I don't know if this is the optimal solution, but it was the one I could find.

### CODE REVIEW

**Comment by jonasborggren** [comment]
When can I expect a new version with this fix? It's breaking my builds!

**Comment by JaeungHyun** [comment]
@jonasborggren open that file and just fix yourself. Then it works!

**Comment by shiweiwei114** [comment]
> @jonasborggren open that file and just fix yourself. Then it works!

hmm but I changed this file that is in .pubcache, all my teammates have to do the same when they check out the code. And I prefer not to bring this package locally. Do you have another way to change it?

**Comment by shiweiwei114** [comment]
> > > @jonasborggren open that file and just fix yourself. Then it works!
> > 
> > 
> > hmm but I changed this file that is in .pubcache, all my teammates have to do the same when they check out the code. And I prefer not to bring this package locally. Do you have another way to change it?
> 
> Fork this repo and fix it. and add pubspec.yaml with your repo address

Thanks! I just did this: https://github.com/CasperPas/flutter-sound-stream/issues/47#issuecomment-1181615070. It seems someone already did it. :)

**Pull request closed without merging**
